name: csslib
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/csslib
description: A library for working with CSS.
version: 0.0.1
dependencies:
  unittest: { sdk: unittest }
  args: { sdk: args }
  logging: { sdk: logging }
