name: csslib
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/csslib
description: A library for parsing CSS.
version: 0.3.4
dependencies:
  args: any
  logging: any
  unittest: any
  pathos: any
  source_maps: ">=0.3.2 <0.3.3"
  # used to parse test-suites code
  html5lib: any
environment:
  sdk: ">=0.3.7+5.r18669"
